# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170126_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='var'),
            preserve_default=False,
        ),
    ]
